import { TemplateDefinition } from "@/types/template";

export const BUILTIN_TEMPLATES: TemplateDefinition[] = [
  // -------------------------------------------------------------
  // TEMPLATE 1: BOLD MINIMALIST SHOWCASE
  // -------------------------------------------------------------
  {
    id: "tpl-bold-minimal",
    name: "Minimalist Product Showcase",
    category: "products",
    description: "Ultra-clean modern layout with hero image focus, floating brand badge, bold headline, and custom CTA.",
    thumbnailUrl: "/templates/thumbnails/minimal-product.svg",
    layouts: {
      SQUARE_1_1: {
        width: 1080,
        height: 1080,
        backgroundColor: "#FFFFFF",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 40,
            y: 160,
            width: 1000,
            height: 720,
            zIndex: 1,
            fit: "cover",
            borderRadius: 24,
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 60,
            y: 50,
            width: 220,
            height: 70,
            zIndex: 3,
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Discover Premium Essentials",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 44,
            fontWeight: 800,
            textAlign: "left",
            x: 60,
            y: 910,
            width: 660,
            height: 110,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Shop Collection",
            bgToken: "primary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 36,
            paddingY: 18,
            fontSize: 22,
            x: 750,
            y: 935,
            width: 270,
            height: 64,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram"],
            layout: "horizontal",
            colorToken: "secondary",
            fontSize: 20,
            gap: 40,
            x: 600,
            y: 70,
            width: 420,
            height: 40,
            zIndex: 3,
          },
        ],
      },

      STORY_9_16: {
        width: 1080,
        height: 1920,
        backgroundColor: "#FFFFFF",
        elements: [
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 60,
            y: 120,
            width: 240,
            height: 80,
            zIndex: 3,
            preserveAspect: true,
          },
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 50,
            y: 260,
            width: 980,
            height: 1280,
            zIndex: 1,
            fit: "cover",
            borderRadius: 36,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Discover Premium Essentials",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 54,
            fontWeight: 800,
            textAlign: "center",
            x: 60,
            y: 1590,
            width: 960,
            height: 130,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Shop Collection",
            bgToken: "primary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 44,
            paddingY: 22,
            fontSize: 26,
            x: 340,
            y: 1740,
            width: 400,
            height: 76,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["instagram", "website"],
            layout: "horizontal",
            colorToken: "secondary",
            fontSize: 22,
            gap: 40,
            x: 260,
            y: 1845,
            width: 560,
            height: 40,
            zIndex: 3,
          },
        ],
      },

      PORTRAIT_4_5: {
        width: 1080,
        height: 1350,
        backgroundColor: "#FFFFFF",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 40,
            y: 170,
            width: 1000,
            height: 940,
            zIndex: 1,
            fit: "cover",
            borderRadius: 28,
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 60,
            y: 60,
            width: 220,
            height: 70,
            zIndex: 3,
            preserveAspect: true,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram"],
            layout: "horizontal",
            colorToken: "secondary",
            fontSize: 20,
            gap: 30,
            x: 580,
            y: 80,
            width: 440,
            height: 40,
            zIndex: 3,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Discover Premium Essentials",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 48,
            fontWeight: 800,
            textAlign: "left",
            x: 60,
            y: 1150,
            width: 660,
            height: 120,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Shop Collection",
            bgToken: "primary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 36,
            paddingY: 18,
            fontSize: 22,
            x: 750,
            y: 1180,
            width: 270,
            height: 66,
            zIndex: 3,
          },
        ],
      },

      LANDSCAPE_16_9: {
        width: 1920,
        height: 1080,
        backgroundColor: "#FFFFFF",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 880,
            y: 60,
            width: 980,
            height: 960,
            zIndex: 1,
            fit: "cover",
            borderRadius: 32,
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 100,
            y: 120,
            width: 280,
            height: 80,
            zIndex: 3,
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Discover Premium Essentials",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 64,
            fontWeight: 800,
            textAlign: "left",
            x: 100,
            y: 380,
            width: 720,
            height: 220,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Shop Collection",
            bgToken: "primary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 48,
            paddingY: 22,
            fontSize: 26,
            x: 100,
            y: 680,
            width: 320,
            height: 74,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram", "phone"],
            layout: "horizontal",
            colorToken: "secondary",
            fontSize: 22,
            gap: 40,
            x: 100,
            y: 920,
            width: 700,
            height: 50,
            zIndex: 3,
          },
        ],
      },
    },
  },

  // -------------------------------------------------------------
  // TEMPLATE 2: PROMOTIONAL FLASH SALE & OFFER
  // -------------------------------------------------------------
  {
    id: "tpl-flash-sale",
    name: "Bold Promo & Flash Sale",
    category: "promotions",
    description: "High-contrast card banner with color frame, urgency headline, promotional badge, and social strip.",
    thumbnailUrl: "/templates/thumbnails/promo-sale.svg",
    layouts: {
      SQUARE_1_1: {
        width: 1080,
        height: 1080,
        backgroundColor: "#0F172A",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 0,
            y: 0,
            width: 1080,
            height: 1080,
            zIndex: 1,
            fit: "cover",
            gradientOverlay: {
              direction: "to-top",
              startColor: "rgba(15, 23, 42, 0.92)",
              endColor: "rgba(15, 23, 42, 0.25)",
            },
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 60,
            y: 60,
            width: 220,
            height: 70,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "offer-pill",
            type: "DECORATIVE_SHAPE",
            shape: "pill",
            colorToken: "accent",
            x: 60,
            y: 650,
            width: 240,
            height: 48,
            zIndex: 3,
            borderRadius: 999,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "LIMITED TIME OFFER: 30% OFF",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 52,
            fontWeight: 900,
            textAlign: "left",
            x: 60,
            y: 720,
            width: 960,
            height: 150,
            zIndex: 3,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Claim Offer Now",
            bgToken: "accent",
            textToken: "dark",
            borderRadius: 16,
            paddingX: 36,
            paddingY: 18,
            fontSize: 24,
            x: 60,
            y: 910,
            width: 320,
            height: 68,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram", "phone"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 20,
            gap: 30,
            x: 430,
            y: 930,
            width: 590,
            height: 40,
            zIndex: 3,
          },
        ],
      },

      STORY_9_16: {
        width: 1080,
        height: 1920,
        backgroundColor: "#0F172A",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 0,
            y: 0,
            width: 1080,
            height: 1920,
            zIndex: 1,
            fit: "cover",
            gradientOverlay: {
              direction: "to-top",
              startColor: "rgba(15, 23, 42, 0.95)",
              endColor: "rgba(15, 23, 42, 0.3)",
            },
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 60,
            y: 120,
            width: 240,
            height: 80,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "SPECIAL SALE\nUP TO 50% OFF",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 68,
            fontWeight: 900,
            textAlign: "center",
            x: 60,
            y: 1350,
            width: 960,
            height: 200,
            zIndex: 3,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Shop Now & Save",
            bgToken: "accent",
            textToken: "dark",
            borderRadius: 999,
            paddingX: 48,
            paddingY: 22,
            fontSize: 26,
            x: 320,
            y: 1600,
            width: 440,
            height: 80,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 24,
            gap: 40,
            x: 240,
            y: 1750,
            width: 600,
            height: 50,
            zIndex: 3,
          },
        ],
      },

      PORTRAIT_4_5: {
        width: 1080,
        height: 1350,
        backgroundColor: "#0F172A",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 0,
            y: 0,
            width: 1080,
            height: 1350,
            zIndex: 1,
            fit: "cover",
            gradientOverlay: {
              direction: "to-top",
              startColor: "rgba(15, 23, 42, 0.94)",
              endColor: "rgba(15, 23, 42, 0.25)",
            },
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 60,
            y: 80,
            width: 220,
            height: 70,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "SPECIAL SALE: 30% OFF",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 58,
            fontWeight: 900,
            textAlign: "left",
            x: 60,
            y: 920,
            width: 960,
            height: 150,
            zIndex: 3,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Claim Discount",
            bgToken: "accent",
            textToken: "dark",
            borderRadius: 16,
            paddingX: 40,
            paddingY: 20,
            fontSize: 24,
            x: 60,
            y: 1100,
            width: 320,
            height: 72,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 22,
            gap: 40,
            x: 440,
            y: 1120,
            width: 580,
            height: 40,
            zIndex: 3,
          },
        ],
      },

      LANDSCAPE_16_9: {
        width: 1920,
        height: 1080,
        backgroundColor: "#0F172A",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 0,
            y: 0,
            width: 1920,
            height: 1080,
            zIndex: 1,
            fit: "cover",
            gradientOverlay: {
              direction: "to-top",
              startColor: "rgba(15, 23, 42, 0.95)",
              endColor: "rgba(15, 23, 42, 0.4)",
            },
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 100,
            y: 100,
            width: 280,
            height: 80,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "MEGA SALE: UP TO 50% OFF",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 76,
            fontWeight: 900,
            textAlign: "left",
            x: 100,
            y: 420,
            width: 1200,
            height: 220,
            zIndex: 3,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Shop The Sale",
            bgToken: "accent",
            textToken: "dark",
            borderRadius: 20,
            paddingX: 52,
            paddingY: 24,
            fontSize: 28,
            x: 100,
            y: 700,
            width: 360,
            height: 84,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram", "phone"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 24,
            gap: 50,
            x: 100,
            y: 920,
            width: 900,
            height: 50,
            zIndex: 3,
          },
        ],
      },
    },
  },

  // -------------------------------------------------------------
  // TEMPLATE 3: RESTAURANT & FOOD SPOTLIGHT
  // -------------------------------------------------------------
  {
    id: "tpl-food-spotlight",
    name: "Gourmet Dish & Menu Feature",
    category: "lifestyle",
    description: "Warm, appetizing layout tailored for food, beverage, hospitality, and artisan retail brands.",
    thumbnailUrl: "/templates/thumbnails/food-spotlight.svg",
    layouts: {
      SQUARE_1_1: {
        width: 1080,
        height: 1080,
        backgroundColor: "#18181B",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 50,
            y: 50,
            width: 980,
            height: 700,
            zIndex: 1,
            fit: "cover",
            borderRadius: 24,
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 80,
            y: 80,
            width: 200,
            height: 60,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Chef's Special: Artisan Truffle Pasta",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 42,
            fontWeight: 700,
            textAlign: "left",
            x: 60,
            y: 800,
            width: 700,
            height: 110,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Reserve Table",
            bgToken: "accent",
            textToken: "white",
            borderRadius: 999,
            paddingX: 32,
            paddingY: 16,
            fontSize: 22,
            x: 770,
            y: 820,
            width: 250,
            height: 62,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["phone", "website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 20,
            gap: 30,
            x: 60,
            y: 980,
            width: 960,
            height: 40,
            zIndex: 3,
          },
        ],
      },

      STORY_9_16: {
        width: 1080,
        height: 1920,
        backgroundColor: "#18181B",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 0,
            y: 0,
            width: 1080,
            height: 1920,
            zIndex: 1,
            fit: "cover",
            gradientOverlay: {
              direction: "to-top",
              startColor: "rgba(24, 24, 27, 0.96)",
              endColor: "rgba(24, 24, 27, 0.2)",
            },
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 60,
            y: 120,
            width: 240,
            height: 80,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Fresh Flavors\nCrafted Daily",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 64,
            fontWeight: 800,
            textAlign: "center",
            x: 60,
            y: 1400,
            width: 960,
            height: 180,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Order Online / Dine In",
            bgToken: "accent",
            textToken: "white",
            borderRadius: 999,
            paddingX: 48,
            paddingY: 22,
            fontSize: 26,
            x: 300,
            y: 1620,
            width: 480,
            height: 80,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["phone", "website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 22,
            gap: 40,
            x: 180,
            y: 1760,
            width: 720,
            height: 50,
            zIndex: 3,
          },
        ],
      },

      PORTRAIT_4_5: {
        width: 1080,
        height: 1350,
        backgroundColor: "#18181B",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 40,
            y: 150,
            width: 1000,
            height: 900,
            zIndex: 1,
            fit: "cover",
            borderRadius: 28,
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 60,
            y: 50,
            width: 220,
            height: 70,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Savor The Finest Cuts & Wine",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 48,
            fontWeight: 800,
            textAlign: "left",
            x: 60,
            y: 1100,
            width: 660,
            height: 120,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "View Full Menu",
            bgToken: "accent",
            textToken: "white",
            borderRadius: 999,
            paddingX: 36,
            paddingY: 18,
            fontSize: 22,
            x: 750,
            y: 1120,
            width: 270,
            height: 66,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["phone", "website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 20,
            gap: 30,
            x: 60,
            y: 1260,
            width: 960,
            height: 40,
            zIndex: 3,
          },
        ],
      },

      LANDSCAPE_16_9: {
        width: 1920,
        height: 1080,
        backgroundColor: "#18181B",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 840,
            y: 60,
            width: 1020,
            height: 960,
            zIndex: 1,
            fit: "cover",
            borderRadius: 32,
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 100,
            y: 120,
            width: 280,
            height: 80,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Experience Culinary Perfection",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 60,
            fontWeight: 800,
            textAlign: "left",
            x: 100,
            y: 400,
            width: 700,
            height: 200,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "Book Your Table",
            bgToken: "accent",
            textToken: "white",
            borderRadius: 999,
            paddingX: 48,
            paddingY: 22,
            fontSize: 26,
            x: 100,
            y: 680,
            width: 320,
            height: 74,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["phone", "website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 22,
            gap: 40,
            x: 100,
            y: 920,
            width: 700,
            height: 50,
            zIndex: 3,
          },
        ],
      },
    },
  },
];

export function getTemplateById(id: string): TemplateDefinition | undefined {
  return BUILTIN_TEMPLATES.find((t) => t.id === id);
}

