import { TemplateDefinition } from "@/types/template";

export const BUILTIN_TEMPLATES: TemplateDefinition[] = [
  // -------------------------------------------------------------
  // TEMPLATE 1: URBAN ATHLETIC RUNNER (From User Mockup)
  // -------------------------------------------------------------
  {
    id: "tpl-urban-wear",
    name: "Urban Athletic Runner",
    category: "products",
    description: "Signature dark gradient card with hero athletic shoe, Urban Wear logo, bold headline, and contact strip.",
    thumbnailUrl: "/templates/thumbnails/urban-shoe.svg",
    layouts: {
      SQUARE_1_1: {
        width: 1080,
        height: 1080,
        backgroundColor: "#0F172A",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 0,
            y: 0,
            width: 1080,
            height: 1080,
            zIndex: 1,
            fit: "cover",
            gradientOverlay: {
              direction: "to-top",
              startColor: "rgba(15, 23, 42, 0.95)",
              endColor: "rgba(15, 23, 42, 0.15)",
            },
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 480,
            y: 80,
            width: 120,
            height: 70,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "STYLE\nTHAT MOVES\nWITH YOU",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 54,
            fontWeight: 900,
            textAlign: "left",
            x: 80,
            y: 650,
            width: 600,
            height: 190,
            zIndex: 3,
            lineHeight: 64,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "white",
            textToken: "dark",
            borderRadius: 999,
            paddingX: 36,
            paddingY: 16,
            fontSize: 22,
            x: 80,
            y: 870,
            width: 220,
            height: 60,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["instagram", "phone"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 20,
            gap: 30,
            x: 80,
            y: 990,
            width: 920,
            height: 40,
            zIndex: 3,
          },
        ],
      },

      STORY_9_16: {
        width: 1080,
        height: 1920,
        backgroundColor: "#0F172A",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 0,
            y: 0,
            width: 1080,
            height: 1920,
            zIndex: 1,
            fit: "cover",
            gradientOverlay: {
              direction: "to-top",
              startColor: "rgba(15, 23, 42, 0.96)",
              endColor: "rgba(15, 23, 42, 0.25)",
            },
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 480,
            y: 120,
            width: 120,
            height: 70,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "STYLE\nTHAT MOVES\nWITH YOU",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 68,
            fontWeight: 900,
            textAlign: "center",
            x: 80,
            y: 1350,
            width: 920,
            height: 220,
            zIndex: 3,
            lineHeight: 78,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "white",
            textToken: "dark",
            borderRadius: 999,
            paddingX: 44,
            paddingY: 20,
            fontSize: 26,
            x: 400,
            y: 1620,
            width: 280,
            height: 72,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["instagram", "phone"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 22,
            gap: 40,
            x: 260,
            y: 1780,
            width: 560,
            height: 40,
            zIndex: 3,
          },
        ],
      },

      PORTRAIT_4_5: {
        width: 1080,
        height: 1350,
        backgroundColor: "#0F172A",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 0,
            y: 0,
            width: 1080,
            height: 1350,
            zIndex: 1,
            fit: "cover",
            gradientOverlay: {
              direction: "to-top",
              startColor: "rgba(15, 23, 42, 0.95)",
              endColor: "rgba(15, 23, 42, 0.2)",
            },
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 480,
            y: 90,
            width: 120,
            height: 70,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "STYLE\nTHAT MOVES\nWITH YOU",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 58,
            fontWeight: 900,
            textAlign: "left",
            x: 80,
            y: 880,
            width: 600,
            height: 200,
            zIndex: 3,
            lineHeight: 68,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "white",
            textToken: "dark",
            borderRadius: 999,
            paddingX: 40,
            paddingY: 18,
            fontSize: 24,
            x: 80,
            y: 1110,
            width: 240,
            height: 64,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["instagram", "phone"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 22,
            gap: 30,
            x: 80,
            y: 1240,
            width: 920,
            height: 40,
            zIndex: 3,
          },
        ],
      },

      LANDSCAPE_16_9: {
        width: 1920,
        height: 1080,
        backgroundColor: "#0F172A",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 0,
            y: 0,
            width: 1920,
            height: 1080,
            zIndex: 1,
            fit: "cover",
            gradientOverlay: {
              direction: "to-top",
              startColor: "rgba(15, 23, 42, 0.95)",
              endColor: "rgba(15, 23, 42, 0.35)",
            },
          },
          {
            id: "brand-logo",
            type: "BRAND_LOGO",
            x: 100,
            y: 80,
            width: 160,
            height: 70,
            zIndex: 3,
            variant: "white",
            preserveAspect: true,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "STYLE THAT MOVES WITH YOU",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 72,
            fontWeight: 900,
            textAlign: "left",
            x: 100,
            y: 480,
            width: 1100,
            height: 180,
            zIndex: 3,
            lineHeight: 84,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "white",
            textToken: "dark",
            borderRadius: 999,
            paddingX: 48,
            paddingY: 22,
            fontSize: 26,
            x: 100,
            y: 720,
            width: 280,
            height: 74,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["instagram", "phone", "website"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 24,
            gap: 50,
            x: 100,
            y: 930,
            width: 1000,
            height: 50,
            zIndex: 3,
          },
        ],
      },
    },
  },

  // -------------------------------------------------------------
  // TEMPLATE 2: BIG SALE UP TO 50% OFF
  // -------------------------------------------------------------
  {
    id: "tpl-big-sale",
    name: "Big Sale Promo",
    category: "promotions",
    description: "Vibrant coral/orange promo poster with large discount callout and urgency badges.",
    thumbnailUrl: "/templates/thumbnails/big-sale.svg",
    layouts: {
      SQUARE_1_1: {
        width: 1080,
        height: 1080,
        backgroundColor: "#FF5A36",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 60,
            y: 60,
            width: 960,
            height: 580,
            zIndex: 1,
            fit: "cover",
            borderRadius: 24,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "BIG SALE\nUP TO 50% OFF",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 64,
            fontWeight: 900,
            textAlign: "left",
            x: 60,
            y: 690,
            width: 650,
            height: 180,
            zIndex: 3,
            lineHeight: 74,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "dark",
            textToken: "white",
            borderRadius: 999,
            paddingX: 36,
            paddingY: 18,
            fontSize: 22,
            x: 60,
            y: 890,
            width: 240,
            height: 64,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 20,
            gap: 30,
            x: 60,
            y: 990,
            width: 960,
            height: 40,
            zIndex: 3,
          },
        ],
      },
      STORY_9_16: {
        width: 1080,
        height: 1920,
        backgroundColor: "#FF5A36",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 50,
            y: 200,
            width: 980,
            height: 1100,
            zIndex: 1,
            fit: "cover",
            borderRadius: 36,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "BIG SALE\nUP TO 50% OFF",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 72,
            fontWeight: 900,
            textAlign: "center",
            x: 60,
            y: 1380,
            width: 960,
            height: 200,
            zIndex: 3,
            lineHeight: 84,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "dark",
            textToken: "white",
            borderRadius: 999,
            paddingX: 44,
            paddingY: 22,
            fontSize: 26,
            x: 360,
            y: 1620,
            width: 360,
            height: 76,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 22,
            gap: 40,
            x: 260,
            y: 1780,
            width: 560,
            height: 40,
            zIndex: 3,
          },
        ],
      },
      PORTRAIT_4_5: {
        width: 1080,
        height: 1350,
        backgroundColor: "#FF5A36",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 50,
            y: 100,
            width: 980,
            height: 760,
            zIndex: 1,
            fit: "cover",
            borderRadius: 28,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "BIG SALE: UP TO 50% OFF",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 54,
            fontWeight: 900,
            textAlign: "left",
            x: 60,
            y: 920,
            width: 960,
            height: 140,
            zIndex: 3,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "dark",
            textToken: "white",
            borderRadius: 999,
            paddingX: 40,
            paddingY: 18,
            fontSize: 22,
            x: 60,
            y: 1100,
            width: 260,
            height: 66,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 20,
            gap: 30,
            x: 60,
            y: 1220,
            width: 960,
            height: 40,
            zIndex: 3,
          },
        ],
      },
      LANDSCAPE_16_9: {
        width: 1920,
        height: 1080,
        backgroundColor: "#FF5A36",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 880,
            y: 80,
            width: 960,
            height: 920,
            zIndex: 1,
            fit: "cover",
            borderRadius: 32,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "BIG SALE\nUP TO 50% OFF",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 80,
            fontWeight: 900,
            textAlign: "left",
            x: 100,
            y: 360,
            width: 720,
            height: 240,
            zIndex: 3,
            lineHeight: 92,
            textTransform: "uppercase",
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "dark",
            textToken: "white",
            borderRadius: 999,
            paddingX: 48,
            paddingY: 22,
            fontSize: 26,
            x: 100,
            y: 660,
            width: 300,
            height: 74,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram", "phone"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 22,
            gap: 40,
            x: 100,
            y: 900,
            width: 720,
            height: 40,
            zIndex: 3,
          },
        ],
      },
    },
  },

  // -------------------------------------------------------------
  // TEMPLATE 3: NEW ARRIVAL (Artisan/Footwear)
  // -------------------------------------------------------------
  {
    id: "tpl-new-arrival",
    name: "New Arrival Spotlight",
    category: "products",
    description: "Sleek editorial dark showcase with elegant serif heading for luxury shoes and leather goods.",
    thumbnailUrl: "/templates/thumbnails/new-arrival.svg",
    layouts: {
      SQUARE_1_1: {
        width: 1080,
        height: 1080,
        backgroundColor: "#18181B",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 40,
            y: 160,
            width: 1000,
            height: 720,
            zIndex: 1,
            fit: "cover",
            borderRadius: 24,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "New Arrival",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 48,
            fontWeight: 800,
            textAlign: "left",
            x: 60,
            y: 910,
            width: 660,
            height: 110,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "EXPLORE",
            bgToken: "accent",
            textToken: "white",
            borderRadius: 999,
            paddingX: 36,
            paddingY: 18,
            fontSize: 22,
            x: 750,
            y: 935,
            width: 270,
            height: 64,
            zIndex: 3,
          },
          {
            id: "social-footer",
            type: "SOCIAL_FOOTER",
            items: ["website", "instagram"],
            layout: "horizontal",
            colorToken: "white",
            fontSize: 20,
            gap: 40,
            x: 60,
            y: 80,
            width: 960,
            height: 40,
            zIndex: 3,
          },
        ],
      },
      STORY_9_16: {
        width: 1080,
        height: 1920,
        backgroundColor: "#18181B",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 50,
            y: 260,
            width: 980,
            height: 1280,
            zIndex: 1,
            fit: "cover",
            borderRadius: 36,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "New Arrival",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 64,
            fontWeight: 800,
            textAlign: "center",
            x: 60,
            y: 1590,
            width: 960,
            height: 130,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "EXPLORE",
            bgToken: "accent",
            textToken: "white",
            borderRadius: 999,
            paddingX: 44,
            paddingY: 22,
            fontSize: 26,
            x: 360,
            y: 1740,
            width: 360,
            height: 76,
            zIndex: 3,
          },
        ],
      },
      PORTRAIT_4_5: {
        width: 1080,
        height: 1350,
        backgroundColor: "#18181B",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 40,
            y: 170,
            width: 1000,
            height: 940,
            zIndex: 1,
            fit: "cover",
            borderRadius: 28,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "New Arrival",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 52,
            fontWeight: 800,
            textAlign: "left",
            x: 60,
            y: 1150,
            width: 660,
            height: 120,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "EXPLORE",
            bgToken: "accent",
            textToken: "white",
            borderRadius: 999,
            paddingX: 36,
            paddingY: 18,
            fontSize: 22,
            x: 750,
            y: 1180,
            width: 270,
            height: 66,
            zIndex: 3,
          },
        ],
      },
      LANDSCAPE_16_9: {
        width: 1920,
        height: 1080,
        backgroundColor: "#18181B",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 880,
            y: 60,
            width: 980,
            height: 960,
            zIndex: 1,
            fit: "cover",
            borderRadius: 32,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "New Arrival",
            fontToken: "heading",
            colorToken: "white",
            fontSize: 72,
            fontWeight: 800,
            textAlign: "left",
            x: 100,
            y: 420,
            width: 720,
            height: 200,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "EXPLORE",
            bgToken: "accent",
            textToken: "white",
            borderRadius: 999,
            paddingX: 48,
            paddingY: 22,
            fontSize: 26,
            x: 100,
            y: 680,
            width: 320,
            height: 74,
            zIndex: 3,
          },
        ],
      },
    },
  },

  // -------------------------------------------------------------
  // TEMPLATE 4: SPECIAL OFFER (Casual & Retail)
  // -------------------------------------------------------------
  {
    id: "tpl-special-offer",
    name: "Special Offer Banner",
    category: "promotions",
    description: "Warm peach card layout highlighting limited-time seasonal collections.",
    thumbnailUrl: "/templates/thumbnails/special-offer.svg",
    layouts: {
      SQUARE_1_1: {
        width: 1080,
        height: 1080,
        backgroundColor: "#FFF1EE",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 60,
            y: 60,
            width: 960,
            height: 640,
            zIndex: 1,
            fit: "cover",
            borderRadius: 24,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "SPECIAL OFFER\nOnly This Week",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 52,
            fontWeight: 800,
            textAlign: "left",
            x: 60,
            y: 740,
            width: 650,
            height: 160,
            zIndex: 3,
            lineHeight: 62,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "secondary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 36,
            paddingY: 18,
            fontSize: 22,
            x: 60,
            y: 920,
            width: 240,
            height: 64,
            zIndex: 3,
          },
        ],
      },
      STORY_9_16: {
        width: 1080,
        height: 1920,
        backgroundColor: "#FFF1EE",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 50,
            y: 200,
            width: 980,
            height: 1150,
            zIndex: 1,
            fit: "cover",
            borderRadius: 36,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "SPECIAL OFFER",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 68,
            fontWeight: 800,
            textAlign: "center",
            x: 60,
            y: 1420,
            width: 960,
            height: 160,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "secondary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 44,
            paddingY: 22,
            fontSize: 26,
            x: 360,
            y: 1640,
            width: 360,
            height: 76,
            zIndex: 3,
          },
        ],
      },
      PORTRAIT_4_5: {
        width: 1080,
        height: 1350,
        backgroundColor: "#FFF1EE",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 50,
            y: 80,
            width: 980,
            height: 820,
            zIndex: 1,
            fit: "cover",
            borderRadius: 28,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "SPECIAL OFFER",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 54,
            fontWeight: 800,
            textAlign: "left",
            x: 60,
            y: 950,
            width: 960,
            height: 120,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "secondary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 40,
            paddingY: 18,
            fontSize: 22,
            x: 60,
            y: 1120,
            width: 260,
            height: 66,
            zIndex: 3,
          },
        ],
      },
      LANDSCAPE_16_9: {
        width: 1920,
        height: 1080,
        backgroundColor: "#FFF1EE",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 880,
            y: 80,
            width: 960,
            height: 920,
            zIndex: 1,
            fit: "cover",
            borderRadius: 32,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "SPECIAL OFFER",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 76,
            fontWeight: 800,
            textAlign: "left",
            x: 100,
            y: 400,
            width: 720,
            height: 200,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP NOW",
            bgToken: "secondary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 48,
            paddingY: 22,
            fontSize: 26,
            x: 100,
            y: 680,
            width: 300,
            height: 74,
            zIndex: 3,
          },
        ],
      },
    },
  },

  // -------------------------------------------------------------
  // TEMPLATE 5: ELEGANT & MODERN (Luxury Bag / Fashion)
  // -------------------------------------------------------------
  {
    id: "tpl-elegant-bag",
    name: "Elegant & Modern Bag",
    category: "lifestyle",
    description: "Refined beige and stone layout designed for luxury leather handbags and high-end fashion.",
    thumbnailUrl: "/templates/thumbnails/elegant-bag.svg",
    layouts: {
      SQUARE_1_1: {
        width: 1080,
        height: 1080,
        backgroundColor: "#F8F6F2",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 60,
            y: 60,
            width: 960,
            height: 640,
            zIndex: 1,
            fit: "cover",
            borderRadius: 24,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Elegant & Modern",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 48,
            fontWeight: 700,
            textAlign: "left",
            x: 60,
            y: 750,
            width: 650,
            height: 120,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP COLLECTION",
            bgToken: "primary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 36,
            paddingY: 18,
            fontSize: 22,
            x: 60,
            y: 910,
            width: 300,
            height: 64,
            zIndex: 3,
          },
        ],
      },
      STORY_9_16: {
        width: 1080,
        height: 1920,
        backgroundColor: "#F8F6F2",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 50,
            y: 220,
            width: 980,
            height: 1180,
            zIndex: 1,
            fit: "cover",
            borderRadius: 36,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Elegant & Modern",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 64,
            fontWeight: 700,
            textAlign: "center",
            x: 60,
            y: 1460,
            width: 960,
            height: 140,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP COLLECTION",
            bgToken: "primary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 44,
            paddingY: 22,
            fontSize: 24,
            x: 340,
            y: 1660,
            width: 400,
            height: 76,
            zIndex: 3,
          },
        ],
      },
      PORTRAIT_4_5: {
        width: 1080,
        height: 1350,
        backgroundColor: "#F8F6F2",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 50,
            y: 80,
            width: 980,
            height: 840,
            zIndex: 1,
            fit: "cover",
            borderRadius: 28,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Elegant & Modern",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 52,
            fontWeight: 700,
            textAlign: "left",
            x: 60,
            y: 960,
            width: 960,
            height: 120,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP COLLECTION",
            bgToken: "primary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 40,
            paddingY: 18,
            fontSize: 22,
            x: 60,
            y: 1120,
            width: 300,
            height: 66,
            zIndex: 3,
          },
        ],
      },
      LANDSCAPE_16_9: {
        width: 1920,
        height: 1080,
        backgroundColor: "#F8F6F2",
        elements: [
          {
            id: "hero-img",
            type: "IMAGE_SLOT",
            x: 880,
            y: 80,
            width: 960,
            height: 920,
            zIndex: 1,
            fit: "cover",
            borderRadius: 32,
          },
          {
            id: "headline-text",
            type: "TEXT_SLOT",
            role: "headline",
            defaultText: "Elegant & Modern",
            fontToken: "heading",
            colorToken: "text",
            fontSize: 72,
            fontWeight: 700,
            textAlign: "left",
            x: 100,
            y: 400,
            width: 720,
            height: 200,
            zIndex: 3,
          },
          {
            id: "cta-badge",
            type: "BADGE_CTA",
            defaultText: "SHOP COLLECTION",
            bgToken: "primary",
            textToken: "white",
            borderRadius: 999,
            paddingX: 48,
            paddingY: 22,
            fontSize: 26,
            x: 100,
            y: 680,
            width: 340,
            height: 74,
            zIndex: 3,
          },
        ],
      },
    },
  },
];

export function getTemplateById(id: string): TemplateDefinition | undefined {
  return BUILTIN_TEMPLATES.find((t) => t.id === id);
}
